routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/welcoming', function () {
    return view('welcoming');
});

Route::get('/register', function () {
    return view('register');
});

Route::post('/form_post', 'AuthController@form_post');

Route::get('/master', function(){
    return view('adminlte.master');
});

Route::get('/items',function(){
    return view('items.index');
});

Route::get('/data-tables',function(){
    return view('adminlte.partials.data-tables');
});

// Route::get('/pertanyaan','PertanyaanController@index');
// Route::get('/pertanyaan/create','PertanyaanController@create');
// Route::post('/pertanyaan','PertanyaanController@store');
// Route::get('/pertanyaan/{id}','PertanyaanController@show');
// Route::get('/pertanyaan/{id}/edit','PertanyaanController@edit');
// Route::put('/pertanyaan/{id}','PertanyaanController@update');
// Route::delete('/pertanyaan/{id}','PertanyaanController@destroy');

Route::resource('pertanyaan','PertanyaanController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/test-dompdf', function(){
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Route::get('export/', 'PertanyaanController@export');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/demo-filemgr',function(){
    return view('file-manager.demo');
});

app/Pertanyaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pertanyaan extends Model
{
    protected $table = 'pertanyaan';
    protected $guarded = ['id'];

    public function user(){
        return $this->belongsTo('App\User','profil_id');
    }

    public function jawabanTepat(){
        return $this->hasOne('App\Jawaban','jawaban_tepat_id');
    }

    public function tag(){
        return $this->belongsToMany('App\Tag');
    }
}

app/Http/Controllers/PertanyaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Pertanyaan;
use App\Profil;
Use Auth;
use App\Tag;
use App\Exports\PertanyaanExport;
use Maatwebsite\Excel\Facades\Excel;
use Alert;

class PertanyaanController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth') -> except(['index','export']) ;
    }

    public function index(){
        // $data_pertanyaan = DB::table('pertanyaan')
        //                     ->join('profil','pertanyaan.profil_id','=','profil.id')
        //                     ->select('pertanyaan.*','profil.nama_lengkap')
        //                     ->orderBy('pertanyaan.id', 'asc')
        //                     ->get();

        $user = Auth::user();

        $data_pertanyaan = $user -> pertanyaan;
        // dd($data_pertanyaan[0]->user->name);
        return view('pertanyaan.index', compact('data_pertanyaan'));
    }

    public function create(){
        return view('pertanyaan.create');
    }

    public function store(Request $request){
        // dd($request->all());
        date_default_timezone_set('Asia/Jakarta');
        $request->validate([
            'judul_pertanyaan' => 'required|max:255',
            'isi_pertanyaan' => 'required'
        ]);
        // $query = DB::table('pertanyaan')->insertGetId(
        //     ['profil_id' => $request['profil_id'],
        //     'judul' => $request['judul_pertanyaan'],
        //     'isi'=> $request['isi_pertanyaan'],
        //     'tanggal_dibuat' => date('y/m/d')
        //     // 'profil_id' => $request['inputProfilId']
        // ]);
        // return redirect('/pertanyaan')->with('success', 'Pertanyaan berhasil disimpan!')  ;

        // $pertanyaan = new Pertanyaan;
        // $pertanyaan -> profil_id = $request['profil_id'];
        // $pertanyaan -> judul = $request['judul_pertanyaan'];
        // $pertanyaan -> isi = $request['isi_pertanyaan'];
        // $pertanyaan -> tanggal_dibuat = date('y/m/d');
        // $pertanyaan -> save();

        $tags_arr = explode(',',$request['tag']);

        $tag_ids = [];
        foreach($tags_arr as $tag_name){
            $tag = Tag::firstOrCreate(['tag' => $tag_name]);
            $tag_ids[] = $tag->id;
            // $tag = Tag::where('tag',$tag_name)->first();
            // if($tag){
            //     $tag_ids[] = $tag->id;
            // } else {
            //     $new_tag = Tag::create(["tag"=>$tag_name]);
            //     $tag_ids[] = $new_tag->id;
            // }
        }
        // dd($tag_ids);

        $user = Auth::user();

        $pertanyaan = $user->pertanyaan() -> create([
            'judul' => $request['judul_pertanyaan'],
            'isi' => $request['isi_pertanyaan'],
            'tanggal_dibuat' => date('y/m/d')

        ]);

        $pertanyaan->tag()->sync($tag_ids);


        Alert::success('Berhasil', 'Pertanyaan berhasil disimpan!');

        return redirect('/pertanyaan')->with('success', 'Pertanyaan berhasil disimpan!');
    }

    public function update($id, Request $request){
        // dd($request->all());
        $request->validate([
            'judul_pertanyaan' => 'required|max:255',
            'isi_pertanyaan' => 'required'
        ]);
        // $query = DB::table('pertanyaan')
        //     -> where('id',$id)
        //     -> update([
        //         'judul' => $request['judul_pertanyaan'],
        //         'isi'=> $request['isi_pertanyaan'],
        //         'tanggal_diperbarui' => date('y/m/d')
        //     ]);
        $pertanyaan = Pertanyaan::find($id) -> update ([
            'judul' => $request['judul_pertanyaan'],
            'isi' => $request['isi_pertanyaan'],
            'tanggal_diperbarui' => date('y/m/d'),
        ]);
        return redirect('/pertanyaan')->with('success', 'Data pertanyaan berhasil diubah!')  ;
    }

    public function show($id){
        // $pertanyaan = DB::table('pertanyaan')
        //             -> join('profil','pertanyaan.profil_id','=','profil.id')
        //             -> select('pertanyaan.*','profil.nama_lengkap','profil.foto')
        //             -> where('pertanyaan.id',$id)
        //             -> first();

        $pertanyaan = Pertanyaan::find($id);
        // dd($pertanyaan->tag()->select('tag')->get());
        return view('pertanyaan.show',compact('pertanyaan'));
    }

    public function edit($id){
        // $pertanyaan = DB::table('pertanyaan')
        //             -> join('profil','pertanyaan.profil_id','=','profil.id')
        //             -> select('pertanyaan.*','profil.nama_lengkap','profil.foto')
        //             -> where('pertanyaan.id',$id)
        //             -> first();

        $pertanyaan = Pertanyaan::with('user')->find($id);
        $tags_arr = [];
        foreach($pertanyaan -> tag as $tag){
            $tags_arr[] = $tag->tag;
        }
        return view('pertanyaan.edit',compact('pertanyaan','tags_arr'));
    }

    public function destroy($id){
        // $pertanyaan = DB::table('pertanyaan')
        //             -> where('id',$id)
        //             -> delete();

        Pertanyaan::destroy($id);
        return redirect('/pertanyaan')->with('success', 'Data berhasil dihapus!')  ;
    }

    public function export()
    {
        return Excel::download(new PertanyaanExport, 'pertanyaan.xlsx');
    }

}

resources/views/pertanyaan/create.blade.php
@extends('adminlte.master')

@push('script-head')

@endpush
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Buat Pertanyaan Baru</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">General Form</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<form role="form" method="POST" action="/pertanyaan">
    @csrf
    <div class="card-body">
        <div class="form-group">
            <label for="inputProfilId">Profil ID</label>
            <input type="text" class="form-control" name= "profil_id" id="inputProfilId" placeholder="Profil ID" value="{{ Auth::id() }}" disabled>
        </div>
        <div class="form-group">
            <label for="userName">Nama Lengkap</label>
            <input type="text" class="form-control" name= "userName" id="userName" placeholder="Nama Lengkap" value="{{ Auth::user() -> name }}" disabled>
        </div>
        <div class="form-group">
            <label for="judulPertanyaan">Judul</label>
            <input type="text" class="form-control" name="judul_pertanyaan" id="judulPertanyaan" placeholder="Judul pertanyaan" value="{{old('judul_pertanyaan','')}}">
            @error('judul_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="tag">Tags</label>
            <input data-role = "tagsinput" type='text' class="form-control" name="tag" id="tag" placeholder="Tags..." value="{{old('tag','')}}">
            @error('tag')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="isi_pertanyaan">Pertanyaan</label>
            <textarea id="isi_pertanyaan" name="isi_pertanyaan" class="my-editor form-control" rows="15">{!! old('isi_pertanyaan', '') !!}</textarea>
            @error('isi_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

@endsection

@push('script')
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea.my-editor",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>

@endpush

resources/views/pertanyaan/edit.blade.php
@extends('adminlte.master')
@push('script-head')
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
@endpush

@section('content')
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Edit Pertanyaan {{ $pertanyaan->id }} </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">General Form</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<form role="form" method="POST" action="/pertanyaan/{{ $pertanyaan->id }} ">
    @csrf
    @method('PUT')
    <div class="card-body">
        <div class="form-group">
            <label for="profilId">Profil ID</label>
            <input type="text" class="form-control" name= "profil_id" id="profilId" value="{{ $pertanyaan -> profil_id }}" disabled>
        </div>
        <div class="form-group">
            <label for="namaLengkap">Nama Lengkap</label>
            <input type="text" class="form-control" name= "namaLengkap" id="namaLengkap" value="{{ $pertanyaan -> user['name'] }}" disabled>
        </div>
        <div class="form-group">
            <label for="judulPertanyaan">Judul</label>
            <input type="text" class="form-control" name="judul_pertanyaan" id="judulPertanyaan" placeholder="Judul pertanyaan" value="{{old('judul_pertanyaan',$pertanyaan -> judul)}}">
            @error('judul_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="tag">Tags</label>
            <input data-role = "tagsinput" type='text' class="form-control" name="tag" id="tag" placeholder="Tags..." value="{{ implode(',',$tags_arr) }}">
            @error('tag')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="isiPertanyaan">Pertanyaan</label>
            <textarea class="my-editor form-control" name="isi_pertanyaan" id="isiPertanyaan" rows = "10" placeholder="Pertanyaan anda...">{{old('isi_pertanyaan',$pertanyaan -> isi)}}</textarea>
            @error('isi_pertanyaan')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
    </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>

@endsection

@push('script')
    <script>
    var editor_config = {
        path_absolute : "/",
        selector: "textarea.my-editor",
        plugins: [
        "advlist autolink lists link image charmap print preview hr anchor pagebreak",
        "searchreplace wordcount visualblocks visualchars code fullscreen",
        "insertdatetime media nonbreaking save table contextmenu directionality",
        "emoticons template paste textcolor colorpicker textpattern"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
        relative_urls: false,
        file_browser_callback : function(field_name, url, type, win) {
        var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
        var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

        var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
        if (type == 'image') {
            cmsURL = cmsURL + "&type=Images";
        } else {
            cmsURL = cmsURL + "&type=Files";
        }

        tinyMCE.activeEditor.windowManager.open({
            file : cmsURL,
            title : 'Filemanager',
            width : x * 0.8,
            height : y * 0.8,
            resizable : "yes",
            close_previous : "no"
        });
        }
    };

    tinymce.init(editor_config);
    </script>
@endpush

resources/views/pertanyaan/index.blade.php
@extends('adminlte.master')

@section('content')
    <div class="card">
        <div class="card-header">
            <h1 class="card-title">Data Pertanyaan</h1>
            <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">
                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            @if(session('success'))
                <div class="alert alert-success ml-2" role="alert">
                    {{ session('success') }}
                </div>
            @endif
            <a class="btn btn-primary mb-2 ml-2 mt-2" href=" {{route('pertanyaan.create')}} ">Buat pertanyaan baru</a>
            <table class="table table-head-fixed">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Profil ID</th>
                        <th>Nama</th>
                        <th>Judul</th>
                        <th>Pertanyaan</th>
                        <th>Tanggal Dibuat</th>
                        <th>Tanggal Diperbarui</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($data_pertanyaan as $key => $value)
                    <tr>
                        <td> </td>
                        <td> {{ $value -> profil_id }} </td>
                        <td> {{ $value -> user['name'] }} </td>
                        <td> {{ $value -> judul }} </td>
                        <td> {!! $value -> isi !!} </td>
                        <td> {{ $value -> tanggal_dibuat }} </td>
                        <td> {{ $value -> tanggal_diperbarui }} </td>
                        <td style="display:flex">
                            <a href=" {{route('pertanyaan.show', ['pertanyaan' => $value->id] )}} "  type="button" class="btn btn-primary btn-sm">show</a>
                            <a href=" {{route('pertanyaan.edit', ['pertanyaan' => $value->id] )}} "  type="button" class="btn btn-dark btn-sm ml-1">edit</a>
                            <form action=" {{route('pertanyaan.destroy', ['pertanyaan' => $value->id] )}} " method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" value="delete" class="btn btn-danger btn-sm ml-1">
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>


@endsection

resources/views/pertanyaan/show.blade.php
@extends('adminlte.master')

@section('content')

    <div class="card card-widget">
        <div class="card-header">
            <div class="user-block">
                <img class="img-circle" src="{{asset('adminlte/dist/img/user1-128x128.jpg')}}" alt="User Image">
                <span class="username"><a href="#"> {{$pertanyaan -> user['name']}} </a></span>
                <span class="description">Shared publicly on {{ $pertanyaan -> tanggal_dibuat }} </span>
            </div>
            <!-- /.user-block -->
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <h3> {{ $pertanyaan -> judul }} </h1>
            @foreach($pertanyaan->tag as $tag)
                <p class="text-muted" style='display:inline'>#{{ $tag->tag }} </p>
            @endforeach
            <p> {{ $pertanyaan -> isi }} </p>
            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-share"></i> Share</button>
            <button type="button" class="btn btn-default btn-sm"><i class="far fa-thumbs-up"></i> Like</button>
            <span class="float-right text-muted">127 likes - 3 comments</span>
        </div>
        <!-- /.card-body -->
        <div class="card-footer card-comments">
            <div class="card-comment">
                <!-- User image -->
                <img class="img-circle img-sm" src="{{asset('adminlte/dist/img/user3-128x128.jpg')}}" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                        Maria Gonzales
                        <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                </div>
                <!-- /.comment-text -->
            </div>
            <!-- /.card-comment -->
            <div class="card-comment">
                <!-- User image -->
                <img class="img-circle img-sm" src="{{asset('adminlte/dist/img/user4-128x128.jpg')}}" alt="User Image">
                <div class="comment-text">
                    <span class="username">
                        Luna Stark
                        <span class="text-muted float-right">8:03 PM Today</span>
                    </span><!-- /.username -->
                    It is a long established fact that a reader will be distracted
                    by the readable content of a page when looking at its layout.
                </div>
                <!-- /.comment-text -->
            </div>
            <!-- /.card-comment -->
        </div>
        <!-- /.card-footer -->
        <div class="card-footer">
            <form action="#" method="post">
                <img class="img-fluid img-circle img-sm" src="{{asset('adminlte/dist/img/user4-128x128.jpg')}}" alt="Alt Text">
                <!-- .img-push is used to add margin to elements next to floating images -->
                <div class="img-push">
                    <input type="text" class="form-control form-control-sm" placeholder="Press enter to post comment">
                </div>
            </form>
        </div>
        <!-- /.card-footer -->
    </div>
@endsection